### ISSUE TITLE
process.nextTick is not a function 

### ISSUE THREAD

**Issue by mmarkell** [Philmod/node-kmeans#15]
Call stack: 
    iterate: kmeans.js:159.30
    Clusterize: kmeans.js:161:11
    clusterize: kmeans.js:234:24

Error Message:
    process.nextTick is not a function. (In process.nextTick(iterate), process.nextTick is undefined.)

Do you have any ideas what might be causing this issue?

**Comment by Philmod** [comment]
Hey Michael,

Do you have a simple way to reproduce this? 
On which OS are you running your code?
Did you google this error?

**Comment by mmarkell** [comment]
From googling, everyone suggested I clear out yarn cache / reinstall all
node modules but it didn’t help. I’m on OS X. Quick fix was just to check
if process was undefined before calling the function, if so setting it to
an empty {}. It seems to have worked as a sketchy workaround!

**Comment by Philmod** [comment]
Yes, it looks to me like a problem with your node/npm/yarn installation. `process` has nothing to do with this specific package. 

Please re-open if I'm wrong.
