### ISSUE TITLE
How to get the output for further process?

### ISSUE THREAD

**Issue by NabilahNor** [Philmod/node-kmeans#17]
Hello,

Sorry for the trouble but I'm very noob with nodejs and things. 
So, I was wondering how can I get the result of the output? I know from the example, it print out the result but I would like to use the result for next process. How do I call the array of result? 

Sorry for my bad english and if you can't understand the question.

Thank you very much,
NN

**Comment by Philmod** [comment]
Hi, you have to use the `res` within the callback: 

```
kmeans.clusterize(vectors, {k: 4}, (err,res) => {
  if (err) console.error(err);
  else console.log('%o',res);
  // HERE! For example:
  res.forEach((cluster) => {
    console.log('centroids: ', res.centroid);
  });
});
```

Does that make sense?

**Comment by olgaisakovafa** [comment]
Hi, thank you. But I get 'centroids:  undefined' from 
console.log('centroids: ', res.centroid);
