### ISSUE TITLE
Client side lib?

### ISSUE THREAD

**Issue by kevincannon** [Philmod/node-kmeans#2]
Hi there,
Great library. I was wondering is there a client-side version of this (or something it was based on) that I could use? I found lots of client-side kmeans libraries, but nothing as nice as this.
Any suggestions?

**Comment by Philmod** [comment]
Hey,

If you are using [Browserify](http://browserify.org/), you shouldn't have any issue using it on the client side.

Otherwise, if you want to make this library easily usable in the front-end, feel free to submit a Pull Request :-)

Thanks,
Philmod

**Comment by kevincannon** [comment]
Hey Philmod,

I think forking it is a bit above my 'designer who pretends to code' skillset. I gave browserify a shot (hadn't heard of it) and worked a treat. Thanks for the tip!

Kevin
