### ISSUE TITLE
About clusters representation

### ISSUE THREAD

**Issue by loretoparisi** [Philmod/node-kmeans#3]
How did you plot the `clusters` graph represented here? 

![687474703a2f2f7777772e6169736861636b2e696e2f7374617469632f696d672f7475742f6b6d65616e732d6578616d706c652e6a7067](https://cloud.githubusercontent.com/assets/163333/13716260/4ea50594-e7da-11e5-8973-dbf1d5ddbfdc.jpeg)

Thank you!

**Comment by Philmod** [comment]
Hey,

There are few [solutions](http://stackoverflow.com/questions/15477008/how-to-create-charts-using-nodejs) out there to create plots on the server.

**Comment by loretoparisi** [comment]
@Philmod thanks! I'm aware of a highcharts module for node, btw I was wondering if the output of your module so the `array` of

```javascript
{
    "centroid": [
      400000,
      98787
    ],
    "cluster": [
      [
        400000,
        98787
      ]
    ],
    "clusterInd": [
      1
    ]
  }
```

was compatible with some specific clustering/scatter plot function etc.
Of course there is always matlab ( https://gist.github.com/loretoparisi/08ffc26151e67ac92029), highcharts suggests a mixed approach recently to this: http://www.highcharts.com/component/content/article/2-news/52-serverside-generated-charts

**Comment by Philmod** [comment]
I didn't think about this module's output to link with a specific plotting tool.

It should be pretty straightforward using the `cluster` sub-objects.

Keep me updated on what you found!

Thanks,
Philippe
