### ISSUE TITLE
Maximum limit clusters

### ISSUE THREAD

**Issue by lukehedger** [Philmod/node-kmeans#6]
Hi @Philmod 

Do you have experience/thoughts on generating k-means clusters with an upper size limit?

Thanks

**Comment by Philmod** [comment]
Hey Luke,

I'm not sure to understand "upper size limit", could you give me an example?

**Comment by lukehedger** [comment]
So - each cluster should have a maximum of X points. If the cluster size is >= X assign a point to another cluster (and, possibly, do not recompute the centroid)

**Comment by Philmod** [comment]
Oh ok, I understand better.

Unfortunately I don't have any experience on this kind of kmeans use. But I would be very curious on how to implement it.
